/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package latVariable;
//ArithmeticDemo
public class App {
    public static void main(String[] args) {
        int x = 20;
        int y = 10;

        int result = x + y;
        System.out.println ( "x + y = " + result);

        result = x - y;
        System.out.println ( "x - y = " + result);

        result = x * y;
        System.out.println ( "x * y = " + result);

        result = x / y;
        System.out.println ( "x / y = " + result);

        result = x % 3;
        System.out.println ( "x % 3 = " + result);
    }
}
